{
 "title": "CMCD",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "session",
    "label": "session",
    "query": "SELECT DISTINCT sid FROM cmcd.cmcd_data;"
   },
   { "name": "interval", "label": "interval", "query": "1s, 5s, 10s, 1m, 5m" }
  ]
 },
 "panels": [
  {
   "title": "Concurrent Plays",
   "type": "stat",
   "description": "Estimated by counting the number of unique video session id (CMCD sid parameter) for the time period specified in Time picker. It is not the same as unique viewers count: since it is only 5 minutes long video constantly played, the same client can finish and start multiple different plays within the time period.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT sid) FROM cmcd.cmcd_data WHERE $__timeFilter(time)"
    }
   ]
  },
  {
   "title": "Rebuffering Percentage",
   "type": "gauge",
   "description": "Calculated as a percentage of requests signalling rebuffering (CMCD bs) to the total number of requests.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COALESCE(SUM(bs),0) / COUNT(*) FROM cmcd.cmcd_data WHERE $__timeFilter(time)"
    }
   ]
  },
  {
   "title": "Average Encoded Bitrate",
   "type": "gauge",
   "description": "Calculated suing average value of CMCD `br`.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(br) FROM cmcd.cmcd_data WHERE $__timeFilter(time)"
    }
   ]
  },
  {
   "title": "Request Maximum Throughput per Session",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "rawSql": "SELECT \n  $__timeGroup(time,${interval}) as time_sec,\n  avg(rtp) as value, \n  sid as metric \nFROM cmcd_data \nWHERE $__timeFilter(time)\nGROUP BY 1, sid\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Buffer Length per Session",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "rawSql": "SELECT \n  $__timeGroup(time,${interval}) as time_sec,\n  avg(bl) as value, \n  sid as metric \nFROM cmcd_data\nGROUP BY 1, sid\nORDER BY 1"
    }
   ]
  }
 ]
}